#!/bin/bash
. test/integration/helper

setup () {
mkdir -p "$ts_test_dir"
input="$ts_test_dir/input"
}

test_series_calc () {
cat > "$input" <<DOC
2010-01-01T00:30:00Z STATE a/one 1
2010-01-01T01:00:00Z STATE a/one 2
2010-01-01T01:00:00Z REQUEST table/0 a/one
DOC

series_calc "$input" | assert_output "\
2010-01-01T01:00:00Z REPLY table/0 a/one
2010-01-01T00:00:00Z REPLY table/0 0
2010-01-01T00:15:00Z REPLY table/0 0
2010-01-01T00:30:00Z REPLY table/0 1
2010-01-01T00:45:00Z REPLY table/0 1
2010-01-01T01:00:00Z REPLY table/0 2
2010-01-01T01:00:00Z REPLY table/0 -
"
}

test_series_calc_with_graph () {
cat > "$input" <<DOC
2010-01-01T00:00:00Z NODE a/one
2010-01-01T00:00:00Z NODE b/one a/one
2010-01-01T00:00:00Z NODE b/two a/one
2010-01-01T00:00:00Z STATE b/one 0
2010-01-01T00:00:00Z STATE b/two 0
2010-01-01T00:30:00Z STATE b/one 1
2010-01-01T00:30:00Z STATE b/two 2
2010-01-01T01:00:00Z STATE b/one 3
2010-01-01T01:00:00Z STATE b/two 4
2010-01-01T01:00:00Z REQUEST table/0 a/one b/one b/two
DOC

series_calc "$input" | assert_output "\
2010-01-01T01:00:00Z REPLY table/0 a/one b/one b/two
2010-01-01T00:00:00Z REPLY table/0 0 0 0
2010-01-01T00:15:00Z REPLY table/0 0 0 0
2010-01-01T00:30:00Z REPLY table/0 3 1 2
2010-01-01T00:45:00Z REPLY table/0 3 1 2
2010-01-01T01:00:00Z REPLY table/0 7 3 4
2010-01-01T01:00:00Z REPLY table/0 - - -
"
}

#
# -c, --config
#

test_series_calc_c_sets_config_dir () {
mkdir -p "$ts_test_dir"
printf "%s\n" "log_level: debug" > "$ts_test_dir/test.yml"
series_calc -c "$ts_test_dir" --dry-run | grep -q "log_level: debug"
}

#
# --dry-run
#

test_series_calc_dry_run_prints_configs_and_exits () {
series_calc --dry-run | grep -q "log_level: debug"
}

#
# -e, --environment
#

test_series_calc_e_sets_runtime_environment () {
series_calc -e development --dry-run | grep -q "log_level: warn"
}

#
# -h
#

test_series_calc_h_prints_help () {
series_calc -h | grep -q "usage: series_calc"
}

#
# -q, --quiet
#

test_series_calc_q_increments_log_level () {
series_calc -qqq --dry-run | grep -q "log_level: error"
}

#
# -v, --verbose
#

test_series_calc_v_decrements_log_level () {
series_calc -vvv --dry-run | grep -q "log_level: debug"
}

. ts
