#!/bin/bash
. test/integration/helper

setup () {
mkdir -p "$ts_test_dir"
input="$ts_test_dir/input"
}

test_series_calc () {
cat > "$input" <<DOC
2010-01-01T00:30:00Z PUT DATA   a/one 1
2010-01-01T01:00:00Z PUT DATA   a/one 2
2010-01-01T01:00:00Z GET VALUES table/0 a/one
DOC

series_calc "$input" | assert_output "\
2010-01-01T01:00:00Z PUT VALUES table/0 a/one
  2010-01-01T00:00:00Z 0
  2010-01-01T00:15:00Z 0
  2010-01-01T00:30:00Z 1
  2010-01-01T00:45:00Z 1
  2010-01-01T01:00:00Z 2

"
}

test_series_calc_with_graph () {
cat > "$input" <<DOC
2010-01-01T00:00:00Z PUT GRAPH  a/one
2010-01-01T00:00:00Z PUT GRAPH  b/one a/one
2010-01-01T00:00:00Z PUT GRAPH  b/two a/one
2010-01-01T00:00:00Z PUT DATA   b/one 0
2010-01-01T00:00:00Z PUT DATA   b/two 0
2010-01-01T00:30:00Z PUT DATA   b/one 1
2010-01-01T00:30:00Z PUT DATA   b/two 2
2010-01-01T01:00:00Z PUT DATA   b/one 3
2010-01-01T01:00:00Z PUT DATA   b/two 4
2010-01-01T01:00:00Z GET VALUES table/0 a/one b/one b/two
DOC

series_calc "$input" | assert_output "\
2010-01-01T01:00:00Z PUT VALUES table/0 a/one b/one b/two
  2010-01-01T00:00:00Z 0 0 0
  2010-01-01T00:15:00Z 0 0 0
  2010-01-01T00:30:00Z 3 1 2
  2010-01-01T00:45:00Z 3 1 2
  2010-01-01T01:00:00Z 7 3 4

"
}

#
# -c, --config
#

test_series_calc_c_sets_config_dir () {
mkdir -p "$ts_test_dir"
printf "%s\n" "log: {level: debug}" > "$ts_test_dir/test.yml"
series_calc -c "$ts_test_dir" --dry-run | grep -q "  level: debug"
}

#
# --dry-run
#

test_series_calc_dry_run_prints_configs_and_exits () {
series_calc --dry-run | grep -q "  level: debug"
}

#
# -e, --environment
#

test_series_calc_e_sets_runtime_environment () {
series_calc -e development --dry-run | grep -q "  level: warn"
}

#
# -h
#

test_series_calc_h_prints_help () {
series_calc -h | grep -q "usage: series_calc"
}

#
# -q, --quiet
#

test_series_calc_q_increments_level () {
series_calc -qqq --dry-run | grep -q "  level: error"
}

#
# -v, --verbose
#

test_series_calc_v_decrements_level () {
series_calc -vvv --dry-run | grep -q "  level: debug"
}

. ts
